### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/generator-talend#1]
Setup all the code and package analysis tools and add the badges to the README

**Comment by jmfrancois** [comment]
* [ ] npm publish (so I can use it)
* [ ] add npm badge to the readme
* [ ] remove the version from the package.json
* [ ] activate semantic release
* [ ] add semantic release badge

**Comment by jmfrancois** [comment]
it seems this addon is not activated on travis. could you please do so ? I'm sure you are admin of this repository

**Comment by jmfrancois** [comment]
done in #9
