### ISSUE TITLE
Integrate React stack ? 

### ISSUE THREAD

**Issue by talend-glorieux** [Talend/generator-talend#3]
I was wondering is it was worth it to include the entire React stack (React/Jest) for every library or if we should let the user add what is needed.

@jmfrancois I'd like to get your opinion on this.

**Comment by frassinier** [comment]
Can it be an option while generating files (with prompt)?

**Comment by talend-glorieux** [comment]
Yes !! Great idea.

**Comment by jmfrancois** [comment]
In fact it depends, because we already have a generator-react-cmf that ship for react.
So I'm afraid it's create confusion but it has to be well defined.

What do you mean by a react lib ?

About the implementation you have two options : 
* option of the CLI
* sub generator (aka yo talend-lib:react)

**Comment by acateland** [comment]
i think creating a lib we shouldn't target an another lib or framework environnement,
test tooling configuration should be generated anyway

**Comment by jmfrancois** [comment]
I had discussion with @StefanLMNG on this and we may rename this generator as generator-talend. What if we want to use this to generate something else ?

our idea:

```
$ yo talend:tcomponent
-> generate TCOMP stuff
$ yo talend:jslib
-> current generator
$ yo talend:reactlib
-> generate a react library
$ yo talend:git
-> add CONTRIBUTING, PR template, .gitignore, LICENSE, ...
```

That fall under the same subject I believe, what should we put in their ?

**Comment by talend-glorieux** [comment]
@jmfrancois Yep, we already talked together about doing a unified frontend generator. I like that idea. Let's rename the repository to generator-talend.
So to resume the generator should be pretty generic letting you generate whatever you want depending on your project.
I'm not sure I'm OK with yeoman generating backend code... I'll have to think about it ;)

**Comment by frassinier** [comment]
TCOMP is Java stuff?

**Comment by jsomsanith** [comment]
For java, they use maven archetype to generate the project. But it would be interesting to have the sub-generation feature (add a component) to stick with the defined naming standard and folder architecture

**Comment by jmfrancois** [comment]
done in #7
